version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sigap-net-controll-app
    restart: unless-stopped
    volumes:
      - ./.env:/var/www/.env
      - storage-data:/var/www/storage
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www
    depends_on:
      - app

volumes:
  storage-data:
